In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [2]:
df = pd.read_excel("Folds5x2_pp.xlsx")
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

* AT - Ambient Temperature
* V - Exhaust Vacuum 
* AP - Ambient Pressure 
* RH - Relative Humidity
* PE - energy output 

> We need to calculate how much energy output we are getting with the help of rest paremeters

In [3]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
X, y

(array([[  14.96,   41.76, 1024.07,   73.17],
        [  25.18,   62.96, 1020.04,   59.08],
        [   5.11,   39.4 , 1012.16,   92.14],
        ...,
        [  31.32,   74.33, 1012.92,   36.48],
        [  24.48,   69.45, 1013.86,   62.39],
        [  21.6 ,   62.52, 1017.23,   67.87]]),
 array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28]))

As per the dataset there is no null value so we can directly split the data and train

### Spliting the dataset

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
# checking the shape of X and y
X[0].ndim, y[0].ndim

(1, 0)

###  buliding the ANN Model

In [6]:

tf.random.set_seed(42)

# Creating model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(100, input_shape = [4], name = "Input_layer"),
    tf.keras.layers.Dense(1, input_shape = [1], name = "output_layer")
], name = "Model_1")

# Compiling model
model.compile(loss = tf.keras.losses.mae,
              optimizer = tf.keras.optimizers.Adam(learning_rate=0.001),
              metrics = ["mae"])

In [8]:
# fit the model
model.fit(X_train, y_train, epochs=100)

Epoch 1/100


240/240 [==============================] - 1s 908us/step - loss: 23.2196 - mae: 23.2196
Epoch 2/100
240/240 [==============================] - 0s 858us/step - loss: 5.4073 - mae: 5.4073
Epoch 3/100
240/240 [==============================] - 0s 887us/step - loss: 5.1529 - mae: 5.1529
Epoch 4/100
240/240 [==============================] - 0s 853us/step - loss: 4.6274 - mae: 4.6274
Epoch 5/100
240/240 [==============================] - 0s 841us/step - loss: 4.6139 - mae: 4.6139
Epoch 6/100
240/240 [==============================] - 0s 843us/step - loss: 4.4962 - mae: 4.4962
Epoch 7/100
240/240 [==============================] - 0s 845us/step - loss: 4.4525 - mae: 4.4525
Epoch 8/100
240/240 [==============================] - 0s 846us/step - loss: 4.4541 - mae: 4.4541
Epoch 9/100
240/240 [==============================] - 0s 845us/step - loss: 4.7092 - mae: 4.7092
Epoch 10/100
240/240 [==============================] - 0s 845us/step - loss: 4.9877 - mae: 4.9877
Epoch 11/100
24

In [7]:
# Shows the layers (Model 1)
model.summary()

Model: "Model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Input_layer (Dense)         (None, 100)               500       
                                                                 
 output_layer (Dense)        (None, 1)                 101       
                                                                 
Total params: 601 (2.35 KB)
Trainable params: 601 (2.35 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [9]:
# Make some predictions
y_pred = model.predict(X_test)
y_pred

60/60 [==============================] - 0s 820us/step


array([[454.18445],
       [436.13025],
       [430.90482],
       ...,
       [478.87173],
       [432.94775],
       [457.04428]], dtype=float32)

In [10]:
y_test.ndim, y_pred.ndim

(1, 2)

In [5]:
def evaluation(y_test, y_pred):
    mae = tf.metrics.mean_absolute_error(y_true = y_test, 
                                         y_pred = tf.squeeze(y_pred)) # Squeeze to remove extra dimension
    mse = tf.metrics.mean_squared_error(y_true = y_test, 
                                         y_pred = tf.squeeze(y_pred))
    
    return mae, mse

In [14]:
# Shows the layers (model 2 changin lr 0.001 -> 0.01)
model.summary()

Model: "Model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Input_layer (Dense)         (None, 100)               500       
                                                                 
 output_layer (Dense)        (None, 1)                 101       
                                                                 
Total params: 601 (2.35 KB)
Trainable params: 601 (2.35 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
# Make some predictions (model 2 changin lr 0.001 -> 0.01)
y_pred_2 = model.predict(X_test)
y_pred_2

60/60 [==============================] - 0s 763us/step


array([[456.03693],
       [437.6327 ],
       [432.42734],
       ...,
       [481.00665],
       [434.47922],
       [458.75232]], dtype=float32)

In [19]:
# Shows the layers (model 3 changing adding another layer)
model.summary()

Model: "Model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Input_layer (Dense)         (None, 100)               500       
                                                                 
 Input_layer_2 (Dense)       (None, 100)               10100     
                                                                 
 output_layer (Dense)        (None, 1)                 101       
                                                                 
Total params: 10701 (41.80 KB)
Trainable params: 10701 (41.80 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
# Make some predictions (model 3 changing adding another layer)
y_pred_3 = model.predict(X_test)
y_pred_3

60/60 [==============================] - 0s 830us/step


array([[460.5734 ],
       [442.086  ],
       [436.9484 ],
       ...,
       [485.4536 ],
       [438.99844],
       [463.1504 ]], dtype=float32)

In [12]:
mae_v1, mse_v1 = evaluation(y_test, y_pred)
mae_v2, mse_v2 = evaluation(y_test, y_pred_2)
mae_v3, mse_v3 = evaluation(y_test, y_pred_3)

(<tf.Tensor: shape=(), dtype=float32, numpy=4.3962727>,
 <tf.Tensor: shape=(), dtype=float32, numpy=31.275087>)

### Comparing the results

In [24]:
model_results = [["Model_1", mae_v1.numpy(), mse_v1.numpy()],
                ["Model_2", mae_v2.numpy(), mse_v2.numpy()],
                ["Model_3", mae_v3.numpy(), mse_v3.numpy()]]

all_results = pd.DataFrame(model_results, columns=["Model", "MAE", "MSE"])
all_results

Model       MAE        MSE
0  Model_1  4.396273  31.275087
1  Model_2  3.989280  25.602091
2  Model_3  5.119936  39.160980

## Optimizing the Model_2

In [6]:
# model 2 changing lr 0.001 -> 0.01

# buliding the ANN Model
tf.random.set_seed(42)

# Creating model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(100, input_shape = [4], name = "Input_layer"),
    tf.keras.layers.Dense(100, input_shape = [4], name = "Input_layer_2"),
    tf.keras.layers.Dense(100, input_shape = [4], name = "Input_layer_3"),
    tf.keras.layers.Dense(1, input_shape = [1], name = "output_layer")
], name = "Model_2")

# Compiling model
model.compile(loss = tf.keras.losses.mae,
              optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),
              metrics = ["mae"])

In [7]:
# fit the model
model.fit(X_train, y_train, epochs=500)

Epoch 1/500


240/240 [==============================] - 2s 1ms/step - loss: 89.9663 - mae: 89.9663
Epoch 2/500
240/240 [==============================] - 0s 1ms/step - loss: 18.6098 - mae: 18.6098
Epoch 3/500
240/240 [==============================] - 0s 1ms/step - loss: 14.1799 - mae: 14.1799
Epoch 4/500
240/240 [==============================] - 0s 1ms/step - loss: 9.3825 - mae: 9.3825
Epoch 5/500
240/240 [==============================] - 0s 1ms/step - loss: 7.9406 - mae: 7.9406
Epoch 6/500
240/240 [==============================] - 0s 1ms/step - loss: 8.4930 - mae: 8.4930
Epoch 7/500
240/240 [==============================] - 0s 1ms/step - loss: 8.0538 - mae: 8.0538
Epoch 8/500
240/240 [==============================] - 0s 1ms/step - loss: 7.3937 - mae: 7.3937
Epoch 9/500
240/240 [==============================] - 0s 1ms/step - loss: 6.8013 - mae: 6.8013
Epoch 10/500
240/240 [==============================] - 0s 1ms/step - loss: 7.5129 - mae: 7.5129
Epoch 11/500
240/240 [=========

240/240 [==============================] - 0s 1ms/step - loss: 4.8802 - mae: 4.8802
Epoch 81/500
240/240 [==============================] - 0s 1ms/step - loss: 5.3621 - mae: 5.3621
Epoch 82/500
240/240 [==============================] - 0s 1ms/step - loss: 5.5400 - mae: 5.5400
Epoch 83/500
240/240 [==============================] - 0s 1ms/step - loss: 5.2505 - mae: 5.2505
Epoch 84/500
240/240 [==============================] - 0s 1ms/step - loss: 5.0228 - mae: 5.0228
Epoch 85/500
240/240 [==============================] - 0s 1ms/step - loss: 4.7791 - mae: 4.7791
Epoch 86/500
240/240 [==============================] - 0s 1ms/step - loss: 5.1566 - mae: 5.1566
Epoch 87/500
240/240 [==============================] - 0s 1ms/step - loss: 4.8237 - mae: 4.8237
Epoch 88/500
240/240 [==============================] - 0s 1ms/step - loss: 5.6760 - mae: 5.6760
Epoch 89/500
240/240 [==============================] - 0s 1ms/step - loss: 5.1757 - mae: 5.1757
Epoch 90/500
240/240 [=====================

240/240 [==============================] - 0s 2ms/step - loss: 5.1806 - mae: 5.1806
Epoch 164/500
240/240 [==============================] - 0s 1ms/step - loss: 4.7856 - mae: 4.7856
Epoch 165/500
240/240 [==============================] - 0s 1ms/step - loss: 4.7152 - mae: 4.7152
Epoch 166/500
240/240 [==============================] - 0s 1ms/step - loss: 4.7187 - mae: 4.7187
Epoch 167/500
240/240 [==============================] - 0s 1ms/step - loss: 4.5753 - mae: 4.5753
Epoch 168/500
240/240 [==============================] - 0s 1ms/step - loss: 4.6346 - mae: 4.6346
Epoch 169/500
240/240 [==============================] - 0s 1ms/step - loss: 62.9722 - mae: 62.9722
Epoch 170/500
240/240 [==============================] - 0s 1ms/step - loss: 155.9220 - mae: 155.9220
Epoch 171/500
240/240 [==============================] - 0s 1ms/step - loss: 5.1405 - mae: 5.1405
Epoch 172/500
240/240 [==============================] - 0s 1ms/step - loss: 4.8260 - mae: 4.8260
Epoch 173/500
240/240 [=====

240/240 [==============================] - 0s 1ms/step - loss: 4.6678 - mae: 4.6678
Epoch 247/500
240/240 [==============================] - 0s 1ms/step - loss: 5.0670 - mae: 5.0670
Epoch 248/500
240/240 [==============================] - 0s 1ms/step - loss: 4.8552 - mae: 4.8552
Epoch 249/500
240/240 [==============================] - 0s 1ms/step - loss: 4.7853 - mae: 4.7853
Epoch 250/500
240/240 [==============================] - 0s 1ms/step - loss: 6.0700 - mae: 6.0700
Epoch 251/500
240/240 [==============================] - 0s 1ms/step - loss: 4.8605 - mae: 4.8605
Epoch 252/500
240/240 [==============================] - 0s 1ms/step - loss: 4.5905 - mae: 4.5905
Epoch 253/500
240/240 [==============================] - 0s 1ms/step - loss: 4.7519 - mae: 4.7519
Epoch 254/500
240/240 [==============================] - 0s 1ms/step - loss: 7.5747 - mae: 7.5747
Epoch 255/500
240/240 [==============================] - 0s 1ms/step - loss: 4.7511 - mae: 4.7511
Epoch 256/500
240/240 [===========

240/240 [==============================] - 0s 1ms/step - loss: 4.9080 - mae: 4.9080
Epoch 330/500
240/240 [==============================] - 0s 1ms/step - loss: 4.6020 - mae: 4.6020
Epoch 331/500
240/240 [==============================] - 0s 1ms/step - loss: 4.7347 - mae: 4.7347
Epoch 332/500
240/240 [==============================] - 0s 1ms/step - loss: 4.5769 - mae: 4.5769
Epoch 333/500
240/240 [==============================] - 0s 1ms/step - loss: 4.5626 - mae: 4.5626
Epoch 334/500
240/240 [==============================] - 0s 1ms/step - loss: 4.7585 - mae: 4.7585
Epoch 335/500
240/240 [==============================] - 0s 1ms/step - loss: 4.6715 - mae: 4.6715
Epoch 336/500
240/240 [==============================] - 0s 1ms/step - loss: 4.4856 - mae: 4.4856
Epoch 337/500
240/240 [==============================] - 0s 1ms/step - loss: 4.7190 - mae: 4.7190
Epoch 338/500
240/240 [==============================] - 0s 1ms/step - loss: 4.6492 - mae: 4.6492
Epoch 339/500
240/240 [===========

240/240 [==============================] - 0s 1ms/step - loss: 4.7273 - mae: 4.7273
Epoch 413/500
240/240 [==============================] - 0s 1ms/step - loss: 4.5096 - mae: 4.5096
Epoch 414/500
240/240 [==============================] - 0s 1ms/step - loss: 4.7943 - mae: 4.7943
Epoch 415/500
240/240 [==============================] - 0s 1ms/step - loss: 4.5115 - mae: 4.5115
Epoch 416/500
240/240 [==============================] - 0s 1ms/step - loss: 4.9074 - mae: 4.9074
Epoch 417/500
240/240 [==============================] - 0s 1ms/step - loss: 4.6691 - mae: 4.6691
Epoch 418/500
240/240 [==============================] - 0s 1ms/step - loss: 171.1257 - mae: 171.1257
Epoch 419/500
240/240 [==============================] - 0s 1ms/step - loss: 5.6792 - mae: 5.6792
Epoch 420/500
240/240 [==============================] - 0s 1ms/step - loss: 5.6521 - mae: 5.6521
Epoch 421/500
240/240 [==============================] - 0s 1ms/step - loss: 4.9726 - mae: 4.9726
Epoch 422/500
240/240 [=======

240/240 [==============================] - 0s 1ms/step - loss: 4.4348 - mae: 4.4348
Epoch 496/500
240/240 [==============================] - 0s 1ms/step - loss: 4.5962 - mae: 4.5962
Epoch 497/500
240/240 [==============================] - 0s 1ms/step - loss: 4.7244 - mae: 4.7244
Epoch 498/500
240/240 [==============================] - 0s 1ms/step - loss: 4.6414 - mae: 4.6414
Epoch 499/500
240/240 [==============================] - 0s 1ms/step - loss: 4.9674 - mae: 4.9674
Epoch 500/500
240/240 [==============================] - 0s 1ms/step - loss: 4.6562 - mae: 4.6562


In [8]:
# Make some predictions by letting see more train data epoch = 500
y_pred_2_1 = model.predict(X_test)
y_pred_2_1

60/60 [==============================] - 0s 932us/step


array([[455.40088],
       [437.22995],
       [432.44232],
       ...,
       [480.07285],
       [434.61005],
       [458.74246]], dtype=float32)

In [30]:
# Make some predictions by letting see more train data + adding another layer
y_pred_2_2 = model.predict(X_test)
y_pred_2_2

60/60 [==============================] - 0s 797us/step


array([[455.84732],
       [437.32993],
       [432.47147],
       ...,
       [480.79495],
       [434.62814],
       [458.93417]], dtype=float32)

In [35]:
# Make some predictions by letting see more train data + adding another layer + another layer
y_pred_2_3 = model.predict(X_test)
y_pred_2_3

60/60 [==============================] - 0s 780us/step


array([[457.6778 ],
       [440.13263],
       [435.2328 ],
       ...,
       [481.909  ],
       [437.37256],
       [461.2503 ]], dtype=float32)

In [36]:
mae_v2_1, mse_v2_1 = evaluation(y_test, y_pred_2_1)
mae_v2_2, mse_v2_2 = evaluation(y_test, y_pred_2_2)
mae_v2_3, mse_v2_3 = evaluation(y_test, y_pred_2_3)


In [37]:
model_results = [["Model_2_1", mae_v2_1.numpy(), mse_v2_1.numpy()],
                ["Model_2_2", mae_v2_2.numpy(), mse_v2_2.numpy()],
                ["Model_2_3", mae_v2_3.numpy(), mse_v2_3.numpy()]]

all_results = pd.DataFrame(model_results, columns=["Model", "MAE", "MSE"])
all_results

Model       MAE        MSE
0  Model_2_1  3.975710  25.312296
1  Model_2_2  3.980269  25.473391
2  Model_2_3  4.119644  25.897701

Model_2_1 is performing really well!

In [46]:
y_pred1 = tf.squeeze(y_pred_2_1)
y_pred2 = tf.squeeze(y_pred_2_2)
y_pred3 = tf.squeeze(y_pred_2_3)
y_pred1.ndim, y_pred3.ndim, y_pred3.ndim

(1, 1, 1)

In [49]:
con_df = pd.concat([pd.DataFrame({"y_test": y_test}),
                   pd.DataFrame({"Model_1" : y_pred1}),
                   pd.DataFrame({"Model_2" : y_pred2}),
                   pd.DataFrame({"Model_3" : y_pred3})], axis = 1)
con_df

y_test     Model_1     Model_2     Model_3
0     455.27  456.032318  455.847321  457.677795
1     436.31  437.590302  437.329926  440.132629
2     440.68  432.658417  432.471466  435.232788
3     434.40  437.455597  437.196930  440.015259
4     482.06  479.630981  479.348114  480.473083
...      ...         ...         ...         ...
1909  430.24  429.472076  429.355682  432.149963
1910  473.20  475.214996  474.941406  476.177399
1911  479.53  481.099182  480.794952  481.908997
1912  435.76  434.863037  434.628143  437.372559
1913  457.10  459.427124  458.934174  461.250305

[1914 rows x 4 columns]

In [9]:
# Saving model_2
model.save("Best_model")

INFO:tensorflow:Assets written to: Best_model\assets


INFO:tensorflow:Assets written to: Best_model\assets


In [10]:
# load in the SavedModel format model
best_model = tf.keras.models.load_model("Best_model")

In [11]:
best_model.summary()

Model: "Model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Input_layer (Dense)         (None, 100)               500       
                                                                 
 Input_layer_2 (Dense)       (None, 100)               10100     
                                                                 
 Input_layer_3 (Dense)       (None, 100)               10100     
                                                                 
 output_layer (Dense)        (None, 1)                 101       
                                                                 
Total params: 20801 (81.25 KB)
Trainable params: 20801 (81.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.summary()

Model: "Model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Input_layer (Dense)         (None, 100)               500       
                                                                 
 Input_layer_2 (Dense)       (None, 100)               10100     
                                                                 
 Input_layer_3 (Dense)       (None, 100)               10100     
                                                                 
 output_layer (Dense)        (None, 1)                 101       
                                                                 
Total params: 20801 (81.25 KB)
Trainable params: 20801 (81.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
